Repository astarte-platform/astarte_data_access, pull requests merged in 2020-03, with the labels that each got.

#16 CI: update Elixir and OTP versions to match .tool-versions
  .github/workflows/build-workflow.yaml
Labels: chore

#15 Remove conform dependency and adapt to skosgra
  lib/astarte_data_access/database.ex
  mix.exs
  mix.lock
  test/data_test.exs
  test/database_test.exs
  test/device_test.exs
  test/interface_test.exs
  test/mappings_test.exs
  test/support/database_test_helper.exs
Labels: chore

#17 Add skogsra data types
  .formatter.exs
  CHANGELOG.md
  config/astarte_data_access.dev.conf
  config/astarte_data_access.schema.exs
  lib/astarte_data_access/config.ex
  lib/astarte_data_access/config/cqex_nodes.ex
  lib/astarte_data_access/config/xandra_nodes.ex
  mix.exs
  mix.lock
  test/database_test.exs
Labels: chore

#19 Update excoveralls and use coveralls action
  .github/workflows/build-workflow.yaml
  mix.lock
Labels: chore, testing

#18 Update :re2, fixing a compilation problem
  CHANGELOG.md
  mix.exs
  mix.lock
Labels: bug

#20 build-workflow: add elixir and otp versions in cache keys
  .github/workflows/build-workflow.yaml
Labels: chore

#21 Prepare 0.11.0 rc.1
  CHANGELOG.md
  mix.exs
  mix.lock
Labels: chore

#22 Retrieve env var using Skogsra
  lib/astarte_data_access/database.ex
Labels: chore

#23 Update skogsra
  mix.lock
Labels: chore
